# Generated by Django 5.0.6 on 2024-07-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=255)),
                ('image', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='avions',
            name='Assurance',
            field=models.DateField(verbose_name='date expir'),
        ),
        migrations.AlterField(
            model_name='avions',
            name='CDN',
            field=models.DateField(verbose_name="date d'expiration "),
        ),
        migrations.AlterField(
            model_name='avions',
            name='Licence_radio',
            field=models.DateField(verbose_name='dete expi'),
        ),
    ]
