# Generated by Django 5.0.6 on 2024-07-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avions',
            name='Assurance',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='avions',
            name='CDN',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='avions',
            name='Licence_radio',
            field=models.DateField(),
        ),
    ]
