# Generated by Django 5.0.6 on 2024-07-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_membres_type_pilote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membres',
            name='Statut',
            field=models.CharField(default='client', max_length=20),
        ),
    ]
