# Generated by Django 5.0.6 on 2024-07-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_membres_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='avions',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='avions',
            name='status',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
