# Generated by Django 5.0.6 on 2024-07-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_avions_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='avions',
            name='Rating',
            field=models.IntegerField(null=True),
        ),
    ]
