# Generated by Django 5.0.6 on 2024-07-08 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_avions_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('client', 'Client'), ('membre', 'Membre')], default='client', max_length=10)),
                ('status_membre', models.CharField(blank=True, max_length=10, null=True)),
                ('etat_pilotage', models.CharField(blank=True, max_length=10, null=True)),
                ('type_pilote', models.CharField(blank=True, max_length=15, null=True)),
                ('type_pilote_licencie', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_abonnement', models.DateField(auto_now_add=True)),
                ('montant_abonnement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Membres',
        ),
    ]
