# Generated by Django 5.0.6 on 2024-07-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_profile_membership_delete_membres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_abonnement',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='montant_abonnement',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
