# Generated by Django 5.0.6 on 2024-07-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_profile_cin_profile_domicile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prenom',
            field=models.CharField(max_length=20),
        ),
    ]
