# Generated by Django 5.0.6 on 2024-07-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_profile_cin_alter_profile_domicile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='carte_validité',
            field=models.DateField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_pilote_licencie',
            field=models.CharField(blank=True, choices=[('instructeur de vol', 'Instructeur de Vol'), ('instructeur de sol', 'Instructeur de Vol'), ('examinateur de vol', 'Eaminateur de Vol')], max_length=80, null=True),
        ),
    ]
