# Generated by Django 5.0.6 on 2024-07-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_profile_carte_validité_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type_pilote_licencie',
            field=models.CharField(blank=True, choices=[('instructeur de vol', 'Instructeur de Vol'), ('instructeur de sol', 'Instructeur de Sol'), ('examinateur de vol', 'Examinateur de Vol')], max_length=80, null=True),
        ),
    ]
