# Generated by Django 5.0.6 on 2024-07-12 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_news_titre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_service', models.CharField(choices=[('vol d initiation', 'VOL D INITATION'), ('vol decouverte', 'VOL DECOUVERTE')], max_length=80, unique=True)),
                ('prix', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_reservation', models.CharField(choices=[('vol d initiation', 'VOL D INITATION'), ('vol decouverte', 'VOL DECOUVERTE')], max_length=80)),
                ('prix', models.IntegerField()),
                ('date', models.DateTimeField(unique=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
    ]
