# Generated by Django 5.0.6 on 2024-07-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_services_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='type_reservation',
            field=models.CharField(choices=[('vol d initiation', 'VOL D INITIATION'), ('vol decouverte', 'VOL DECOUVERTE')], max_length=80),
        ),
    ]
