# Generated by Django 5.0.6 on 2024-07-15 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_reservation_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='avions',
            new_name='avion',
        ),
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='N_carte_stagiaire',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='carte_validité',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='etat_pilotage',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status_membre',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='type_pilote',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='type_pilote_licencie',
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_abonnement', models.DateField(auto_now_add=True, null=True)),
                ('montant_abonnement', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('Inactive', 'Inactive')], default='active', max_length=15)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Pilotes_Licencié',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carte_validité', models.DateField()),
                ('membre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.membre')),
            ],
        ),
        migrations.CreateModel(
            name='Pilotes_Instructeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carte_validité', models.DateField()),
                ('Disponibilité', models.BooleanField()),
                ('pilote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.pilotes_licencié')),
            ],
        ),
        migrations.CreateModel(
            name='Pilotes_Stagiare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_carte_stagiaire', models.CharField(max_length=80, unique=True)),
                ('membre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.membre')),
            ],
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
