# Generated by Django 5.0.6 on 2024-07-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_avions_avion_rename_news_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilotes_instructeur',
            name='Carte_validité',
        ),
        migrations.AddField(
            model_name='pilotes_instructeur',
            name='type',
            field=models.CharField(choices=[('instructeur de vol', 'Instructeur de Vol'), ('instructeur de sol', 'Instructeur de Sol'), ('examinateur de vol', 'Examinateur de Vol')], max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pilotes_instructeur',
            name='Disponibilité',
            field=models.BooleanField(default=1),
        ),
    ]
