# Generated by Django 5.0.6 on 2024-07-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_pilotes_instructeur_carte_validité_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='image',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
