# Generated by Django 5.0.6 on 2024-07-17 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_avion_status_avion_disponibilité'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='Nbrs_places',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='av',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.avion'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='pilote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pilotes_instructeur'),
        ),
    ]
