# Generated by Django 5.0.6 on 2024-07-17 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_reservation_nbr_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='nbr_places',
        ),
    ]
