# Generated by Django 5.0.6 on 2024-07-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_reservation_nbr_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='Status',
            field=models.CharField(choices=[('en attente', 'EN ATTENTE'), ('validé', 'VALIDÉ')], default='en attente', max_length=80),
        ),
    ]
