# Generated by Django 5.0.6 on 2024-07-20 20:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_de_reservation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
