# Generated by Django 5.0.6 on 2024-07-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_reservation_duree_alter_reservation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Status',
            field=models.CharField(choices=[('en attente', 'EN ATTENTE'), ('validé', 'VALIDÉ')], default='en attente', max_length=80),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='type_reservation',
            field=models.CharField(choices=[('vol d initiation', 'VOL D INITIATION'), ('vol decouverte', 'VOL DECOUVERTE')], max_length=80),
        ),
    ]
