# Generated by Django 5.0.6 on 2024-07-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_reservation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='Sent',
            field=models.BooleanField(default=0),
        ),
    ]
