# Generated by Django 5.0.6 on 2024-07-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_reservation_date_reservation_date_arrivé_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='paiement',
            field=models.CharField(choices=[('payé', 'PAYÉ'), ('impayé', 'IMPAYÉ'), ('annulé', 'ANNULÉ')], default='impayé', max_length=80),
        ),
    ]
