# Generated by Django 5.0.6 on 2024-07-25 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_reservation_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biens_Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_paiement', models.CharField(choices=[('chéque', 'Chéque'), ('espèce', 'Espèce'), ('Virement', 'Virement')], max_length=80, null=True)),
                ('prix', models.IntegerField(null=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.reservation')),
            ],
        ),
    ]
