# Generated by Django 5.0.6 on 2024-07-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_biens_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='biens_reservations',
            name='libellé',
            field=models.TextField(null=True),
        ),
    ]
