# Generated by Django 5.0.6 on 2024-07-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_biens_reservations_libellé'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biens_reservations',
            name='prix',
            field=models.IntegerField(),
        ),
    ]
