# Generated by Django 5.0.6 on 2024-07-26 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_biens_reservations_prix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('premium', 'Premium')], max_length=80)),
                ('prix', models.IntegerField()),
                ('Minutes', models.IntegerField(choices=[('600', '600'), ('1200', '1200'), ('2400', '2400')])),
            ],
        ),
        migrations.AddField(
            model_name='membre',
            name='pack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pack'),
        ),
    ]
