# Generated by Django 5.0.6 on 2024-07-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_pack_minutes_alter_pack_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='solde',
            field=models.IntegerField(null=True),
        ),
    ]
