# Generated by Django 5.0.6 on 2024-07-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_membre_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payé_par_pack',
            field=models.BooleanField(default=0),
        ),
    ]
